/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeManager */

#ifndef _Included_NativeManager
#define _Included_NativeManager
#ifdef __cplusplus
extern "C" {
#endif

  
/*
 * Class:     NativeManager
 * Method:    hasValue
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_NativeManager_hasValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeManager
 * Method:    getStringValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeManager_getStringValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeManager
 * Method:    getIntValue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NativeManager_getIntValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeManager
 * Method:    getFloatValue
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_NativeManager_getFloatValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeManager
 * Method:    getBooleanValue
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_NativeManager_getBooleanValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeManager
 * Method:    getListValue
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_NativeManager_getListValue
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeManager
 * Method:    manage
 * Signature: (Ljava/lang/String;BZ)V
 */
JNIEXPORT void JNICALL Java_NativeManager_manage
  (JNIEnv *, jobject, jstring, jbyte, jboolean);

/*
 * Class:     NativeManager
 * Method:    parseFrom
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_NativeManager_parseFrom
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeManager
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeManager_create
  (JNIEnv *, jobject);

/*
 * Class:     NativeManager
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeManager_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
