/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeManager_ParameterType */

#ifndef _Included_NativeManager_ParameterType
#define _Included_NativeManager_ParameterType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
